## 橙光配置 Start ##
# 用户Cookie
Cookie=
# 浏览器标识 可不用修改 / 也可以参考UserAgentList进行修改
User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0
## 橙光配置 End ##

## 消息提示配置 Start ##
# appToken 参考教程
appToken=
# WxPusher 用户id 参考教程
uids=
# url 教程页+问题反馈页 此处为作者的博客，不需要修改
url=https://blog.wenzhao18.top/index.php/java/66rpg-weichat-spider.html
## 消息提示配置 End ##
